// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqhqwuawhxpjwcfclzjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxaHF3dWF3aHhwandjZmNsemprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTk1MjEsImV4cCI6MjA2Mzg5NTUyMX0.K8J1DfnLUgZDi-eN3Xza7DiPcyMjvOXhmGj5TbXsI84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);